name: CI #display name in GitHub's actions tab

on: # events(nested below) that trigger this workflow to run
  push:
    branches: [ main ] #run workflow when commits pushed to main
  pull_request:
    branches: [ main ] #run when PR targeting main is opened/updated so checks before code reaches main, to prevent breakage rather than just reporting it 
  workflow_dispatch: #adds "run workflow" button in UI for manual testing without needing commits

jobs:
  build-and-test: #jobs internal ID chosen by me
    name: Built and test #again, this is the human readable label in UI
    runs-on: ubuntu-latest #requests a fresh Ubuntu VM. alternatives: 'windows-latest' and 'macos-latest'. Ubuntu default usually as its faster/cheaper

    steps: #lists of intructions that run top to bottom on Ubuntu VM
      - name: Check out the repository
        uses: actions/checkout@v7 #clones repo onto new machine (ubuntu vm)

      - name: Set up the .NET 10 SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x' #install the latest (.x) .NET 10 SDK 

      - name: Restore dependencies
        run: dotnet restore #download NuGet packages. When run from repo root, it finds .sln and restores every project, including tests

      - name: Build
        run: dotnet build --configuration Release --no-restore
                          #--configuration Release: build optimised without debug symbols, tests what is shipped, not a debugger
                                                  #--no-restore: we already restored in previous step above, saves time
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
                          #--no-build: resuse output of previous step, rather than recompiling
                                      #--verbosity normal: give enough detail to see which tests ran